### ISSUE TITLE
Emojis do not hide in spoiler tags

### ISSUE THREAD

**Issue by cbrxyz** [scioly/scioly.org#35]
Emojis in spoiler tags show through the spoiler

**Comment by georgemsun** [comment]
Thanks! I fixed it by adding `span.bbcode-spoiler img { opacity: 0; transition: 0.3s; }` and `span.bbcode-spoiler:hover img { opacity: 1; }`. Also made the color of links it spoilers lighter, set to `#82a3d3`.
